### ISSUE TITLE
Missing start property

### ISSUE THREAD

**Issue by bobbyalex** [yiskang/forge-download-translated-pdf-pages#1]
The `start` property is missing in the package.json file and hence npm start wont work.
```
 "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node index.js"
  },
```
I dont have contribute permissions, else I would have created a PR.

**Comment by yiskang** [comment]
Thank you for pointing out, @bobbyalex! I fixed it. :)
